# docker-compose up

version: '3'
services:
  redis:
    image: redis:latest
    container_name: jelly_redis

  mysql:
    image: mysql:latest
    volumes:
      - ./docker/data:/var/lib/mysql/data
    environment:
      MYSQL_USER: jellystore
      MYSQL_PASSWORD:
    container_name: jelly_db
    ports:
      - "3306:3306"

    jellystore:
      # TODO: gcp 에  올리고 이미지를  gcp 에서 받아서 실행 시켜보자
      image: jellystore
      container_name: jellystore
      volumes:
        - ./src:/usr/app/
        - /usr/app/node_modules
      ports:
        - "3000:3000"

