# docker-compose up

version: '3'
services:
  redis:
    image: redis:latest
    container_name: jelly_redis

  mysql:
    image: mysql:latest
    volumes:
      - ./docker/data:/var/lib/mysql/data
    environment:
      MYSQL_USER: jellystore
      MYSQL_PASSWORD:
    container_name: jelly_db
    ports:
      - 3306:3306

